FROM python:3.8-slim

WORKDIR /app

# Copy the local script to the container
COPY scripts/optimise.py /app/optimise.py

# Install necessary Python packages
RUN pip install pandas scikit-learn joblib

# Run the train script
CMD ["python", "optimise.py"]
