apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimization-app
  template:
    metadata:
      labels:
        app: optimization-app
    spec:
      containers:
      - name: optimization-container
        image: terrence123peh/optimization-image:latest
        volumeMounts:
        - name: my-storage
          mountPath: /data
      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: my-pvc